apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: "too-many-replicas-warn"
spec:
  policyName: "too-many-replicas-warn"
  validationActions: [Warn]
  matchResources:
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: default
