apiVersion: v2
name: start
description: A Helm chart for Kubernetes

type: application

version: 1.0.0

dependencies:
  # https://github.com/argoproj/argo-helm/releases
  - name: argo-cd
    version: 7.9.0
    repository: https://argoproj.github.io/argo-helm
  - name: argo-rollouts
    version: 2.39.5
    repository: https://argoproj.github.io/argo-helm
